apiVersion: v1
kind: Service
metadata:
  name: {{ include "xhis-xui.fullname" . }}
  labels:
    {{- include "xhis-xui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if ne .Values.service.type "ClusterIP" }}
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      {{- end}}
  selector:
    {{- include "xhis-xui.selectorLabels" . | nindent 4 }}
